const $ = (s, e=document) => e.querySelector(s);
const presets={spotify:[3000,3000],youtube:[1280,720],instagram:[1080,1350],square:[1080,1080],story:[1080,1920],x:[1500,500]};
let activeEditor=null;
function fileSize(n){return n<1e6?`${Math.round(n/1024)} KB`:`${(n/1e6).toFixed(1)} MB`}
function download(canvas,type,name,quality=.92){canvas.toBlob(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${name || 'studioshift-image'}.${type.split('/')[1].replace('jpeg','jpg')}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)},type,quality)}
function redraw(ed){if(!ed.img)return;const c=ed.canvas,ctx=c.getContext('2d'), tool=ed.dataset.tool;let w=ed.img.naturalWidth,h=ed.img.naturalHeight,angle=ed.angle||0;
 if(tool==='resize'){w=Math.max(1,+$('#width')?.value||w);h=Math.max(1,+$('#height')?.value||h)} else if(tool==='rotate' && Math.abs(angle%180)===90){w=ed.img.naturalHeight;h=ed.img.naturalWidth}
 c.width=w;c.height=h;ctx.clearRect(0,0,w,h);if(tool==='resize'&&ed.bg&&ed.bg!=='transparent'){ctx.fillStyle=ed.bg;ctx.fillRect(0,0,w,h)}
 ctx.save();if(tool==='rotate'){ctx.translate(w/2,h/2);ctx.rotate(angle*Math.PI/180);ctx.scale(ed.flipX?-1:1,ed.flipY?-1:1);const iw=ed.img.naturalWidth,ih=ed.img.naturalHeight;ctx.drawImage(ed.img,-iw/2,-ih/2)}else if(tool==='resize'){let scale=(ed.fit==='cover')?Math.max(w/ed.img.naturalWidth,h/ed.img.naturalHeight):Math.min(w/ed.img.naturalWidth,h/ed.img.naturalHeight);let iw=ed.img.naturalWidth*scale,ih=ed.img.naturalHeight*scale;let x=ed.fit==='cover'?w/2-iw*(ed.focusX??.5):(w-iw)/2;let y=ed.fit==='cover'?h/2-ih*(ed.focusY??.5):(h-ih)/2;ctx.drawImage(ed.img,x,y,iw,ih)}else {if(tool==='enhance')ctx.filter=`brightness(${ed.brightness||100}%) contrast(${ed.contrast||100}%) saturate(${ed.saturation||100}%)`;ctx.drawImage(ed.img,0,0,w,h)}ctx.restore();
 if(ed.info)ed.info.textContent=`${c.width} × ${c.height} px`;
}
function loadFile(ed,file){if(!file)return;const img=new Image();img.onload=()=>{ed.img=img;ed.name=file.name.replace(/\.[^.]+$/,'');ed.file=file;ed.angle=0;ed.flipX=false;ed.flipY=false;$('.upload-zone',ed).classList.add('hidden');$('.editor-body',ed)?.classList.remove('hidden');$('.simple-body',ed)?.classList.remove('hidden');ed.info=$('.image-info',ed);const sum=$('.file-summary',ed);if(sum)sum.textContent=`${file.name}  ·  ${img.naturalWidth} × ${img.naturalHeight}  ·  ${fileSize(file.size)}`;redraw(ed)};img.src=URL.createObjectURL(file)}
function setupEditor(ed){const file=$('input[type=file]',ed);file.addEventListener('change',e=>loadFile(ed,e.target.files[0]));ed.addEventListener('dragover',e=>e.preventDefault());ed.addEventListener('drop',e=>{e.preventDefault();loadFile(ed,e.dataTransfer.files[0])});$('.reset',ed)?.addEventListener('click',()=>{ed.img=null;file.value='';$('.upload-zone',ed).classList.remove('hidden');$('.editor-body',ed)?.classList.add('hidden');$('.simple-body',ed)?.classList.add('hidden')});$('.download',ed)?.addEventListener('click',()=>{if(!ed.img)return;let type=$('#format',ed)?.value||$('.format-select',ed)?.value||'image/png';let q=+$('.quality',ed)?.value/100||.92;download(ed.canvas,type,ed.name,q)});if(ed.dataset.tool!=='resize'){ed.canvas=document.createElement('canvas');}
 const quality=$('.quality',ed);if(quality)quality.addEventListener('input',()=>{$('output',ed).textContent=quality.value+'%'});
 if(ed.dataset.tool==='rotate'){const angle=$('.angle',ed);angle.addEventListener('input',()=>{ed.angle=+angle.value;$('output',ed).textContent=ed.angle+'°';redraw(ed)});$('.quick-actions',ed).addEventListener('click',e=>{let n=e.target.dataset.turn;if(n!==undefined){ed.angle=(ed.angle+(+n)+360)%360;angle.value=ed.angle;$('output',ed).textContent=ed.angle+'°'}if(e.target.classList.contains('flip-x'))ed.flipX=!ed.flipX;if(e.target.classList.contains('flip-y'))ed.flipY=!ed.flipY;redraw(ed)})}
 if(ed.dataset.tool==='enhance'){ed.querySelectorAll('.tune').forEach(input=>input.addEventListener('input',()=>{ed[input.classList[0]]=input.value;input.parentElement.querySelector('output').textContent=input.value+'%';redraw(ed)}))}
}
document.querySelectorAll('.editor').forEach(setupEditor);
const resize=$('.editor[data-tool=resize]');resize.canvas=$('#canvas');resize.fit='contain';resize.bg='transparent';
$('#preset').addEventListener('change',e=>{let p=presets[e.target.value];if(p){$('#width').value=p[0];$('#height').value=p[1];redraw(resize)}});
['width','height'].forEach(id=>$('#'+id).addEventListener('input',()=>redraw(resize)));
$('#fitMode').addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;resize.fit=e.target.dataset.mode;$('#fitMode').querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b===e.target));redraw(resize)});
$('#background').addEventListener('click',e=>{if(e.target.matches('button')){resize.bg=e.target.dataset.color;$('#background').querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b===e.target));redraw(resize)}});$('#colorPicker').addEventListener('input',e=>{resize.bg=e.target.value;$('#background').querySelectorAll('button').forEach(b=>b.classList.remove('selected'));redraw(resize)});
// Older browsers accept nested sections, but pull each virtual page to the main level so every route remains independent.
const pageRoot=document.querySelector('main');[...pageRoot.querySelectorAll('section.page')].forEach(page=>pageRoot.appendChild(page));
function route(){let hash=location.hash.slice(1)||'home';if(!document.getElementById(hash))hash='home';document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===hash));window.scrollTo(0,0)}
document.addEventListener('click',event=>{const link=event.target.closest('a[href^="#"]');if(!link)return;const target=link.getAttribute('href').slice(1);if(!document.getElementById(target))return;event.preventDefault();if(location.hash.slice(1)===target)route();else location.hash=target;});
window.addEventListener('hashchange',route);route();
window.studioShiftRedraw=redraw;
